# Generated by Django 4.2.7 on 2023-12-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_codigo_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_telefono',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
    ]
