# Generated by Django 4.2.7 on 2023-12-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_alter_user_fecha_nacimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="feeling",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
