# Generated by Django 4.2.7 on 2023-12-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(default='user.jpg', upload_to='avatar/contacts/'),
        ),
    ]
