# Generated by Django 4.2.7 on 2023-11-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calender", "0003_remove_activity_description_remove_activity_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
