# Generated by Django 4.2.7 on 2023-11-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calender", "0004_action_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="date",
            field=models.DateField(),
        ),
    ]
