# Generated by Django 4.2.7 on 2023-11-27 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calender", "0006_music_id_music"),
    ]

    operations = [
        migrations.RenameField(
            model_name="music",
            old_name="name",
            new_name="name_music",
        ),
    ]
