# Generated by Django 4.2.7 on 2023-12-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0008_music_category_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='object',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
