# Generated by Django 4.2.7 on 2023-12-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0009_alter_action_video_alter_object_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='name_music',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='music',
            name='category_music',
        ),
        migrations.AddField(
            model_name='music',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
