# Generated by Django 4.2.7 on 2023-12-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0010_rename_name_music_music_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='id_object',
        ),
        migrations.DeleteModel(
            name='Object',
        ),
    ]
